2024-12-08 22:45:20 | ERROR    | __main__:main:141 | Критическая ошибка: [Errno 2] No such file or directory: 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
Traceback (most recent call last):

  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\main.py", line 149, in <module>
    exit_code = main()
                └ <function main at 0x000001144DE1C040>

> File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\main.py", line 111, in main
    login_window = LoginWindow()
                   └ <class 'ui.login_window.LoginWindow'>

  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 35, in __init__
    uic.loadUi(os.path.join(os.path.dirname(__file__), 'login_window.ui'), self)
    │   │      │  │    │    │  │    │       │                              └ <ui.login_window.LoginWindow object at 0x000001144DCDAF80>
    │   │      │  │    │    │  │    │       └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.py'
    │   │      │  │    │    │  │    └ <function dirname at 0x000001144AE9D940>
    │   │      │  │    │    │  └ <module 'ntpath' (frozen)>
    │   │      │  │    │    └ <module 'os' (frozen)>
    │   │      │  │    └ <function join at 0x000001144AE9D620>
    │   │      │  └ <module 'ntpath' (frozen)>
    │   │      └ <module 'os' (frozen)>
    │   └ <function loadUi at 0x000001144D85A7A0>
    └ <module 'PyQt5.uic' from 'C:\\Users\\MrDes\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\Loc...

  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\__init__.py", line 241, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
           │               │               │       │             └ '_rc'
           │               │               │       └ <ui.login_window.LoginWindow object at 0x000001144DCDAF80>
           │               │               └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
           │               └ ''
           └ <class 'PyQt5.uic.Loader.loader.DynamicUILoader'>
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
           │    │     │         └ '_rc'
           │    │     └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
           │    └ <function UIParser.parse at 0x000001144D94C540>
           └ <PyQt5.uic.Loader.loader.DynamicUILoader object at 0x000001144DE79150>
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
               │     └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
               └ <function parse at 0x000001144D93C040>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
    │    │     │       └ None
    │    │     └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
    │    └ <function ElementTree.parse at 0x000001144D912E80>
    └ <xml.etree.ElementTree.ElementTree object at 0x000001144DE79990>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 570, in parse
    source = open(source, "rb")
                  └ 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\login_window.ui'
2024-12-08 22:52:34 | ERROR    | __main__:main:141 | Критическая ошибка: 'NoneType' object has no attribute 'setFocus'
Traceback (most recent call last):

  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\main.py", line 149, in <module>
    exit_code = main()
                └ <function main at 0x000001FE83D8C400>

> File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\main.py", line 111, in main
    login_window = LoginWindow()
                   └ <class 'ui.login_window.LoginWindow'>

  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 87, in __init__
    self.findChild(QLineEdit, 'lastname_input').setFocus()
    │    │         └ <class 'PyQt5.QtWidgets.QLineEdit'>
    │    └ <built-in method findChild>
    └ <ui.login_window.LoginWindow object at 0x000001FE83BFB370>

AttributeError: 'NoneType' object has no attribute 'setFocus'
2024-12-08 23:28:50 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 220, in validate_and_login
    self.lab_window = LabSelectionWindow(user, self.db_manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 49, in __init__
    uic.loadUi(UI_PATH, self)
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\__init__.py", line 241, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
               ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 570, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\lab_selection.ui'
2024-12-08 23:33:11 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 220, in validate_and_login
    self.lab_window = LabSelectionWindow(user, self.db_manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 64, in __init__
    self.populate_labs()
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 75, in populate_labs
    self.lab_list_widget.addItem(item)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LabSelectionWindow' object has no attribute 'lab_list_widget'
2024-12-08 23:33:48 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 220, in validate_and_login
    self.lab_window = LabSelectionWindow(user, self.db_manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 64, in __init__
    self.populate_labs()
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 75, in populate_labs
    self.lab_list_widget.addItem(item)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LabSelectionWindow' object has no attribute 'lab_list_widget'
2024-12-08 23:56:14 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 122, in logout
    login_dialog = StudentLoginDialog()
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\student_login.py", line 23, in __init__
    uic.loadUi(UI_PATH, self)
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\__init__.py", line 241, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
               ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\xml\etree\ElementTree.py", line 570, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MrDes\\OneDrive\\Документы\\GitHub\\student_app_my\\students_app\\ui\\student_login.ui'
2024-12-08 23:58:42 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 215, in validate_and_login
    self.lab_window = LabSelectionWindow(user, self.db_manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 20, in __init__
    self.group = group.split("'")[3] if "'" in group else group
                                        ^^^^^^^^^^^^
TypeError: argument of type 'DatabaseManager' is not iterable
2024-12-09 00:17:12 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\login_window.py", line 215, in validate_and_login
    self.lab_window = LabSelectionWindow(user, self.db_manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 89, in __init__
    self.create_button_panel()
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 163, in create_button_panel
    if 'role' in self.db_manager.user_data and self.db_manager.user_data['role'] == 'teacher':
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DatabaseManager' object has no attribute 'user_data'
2024-12-09 00:19:27 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_test_window.py", line 385, in finish_test
    for i in range(len(self.questions)):
                       ^^^^^^^^^^^^^^
AttributeError: 'LabTestWindow' object has no attribute 'questions'
2024-12-09 00:20:48 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_selection.py", line 301, in start_test
    self.test_window = LabTestWindow(
                       ^^^^^^^^^^^^^^
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\lab_test_window.py", line 22, in __init__
    self.db = DatabaseManager()
              ^^^^^^^^^^^^^^^
NameError: name 'DatabaseManager' is not defined
2024-12-09 00:22:30 | ERROR    | __main__:qt_message_handler:90 | Traceback (most recent call last):
  File "C:\Users\MrDes\OneDrive\Документы\GitHub\student_app_my\students_app\ui\test_results_window.py", line 95, in return_to_main
    self.lab_window = LabSelectionWindow(self.user_data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LabSelectionWindow.__init__() missing 1 required positional argument: 'db_manager'
2024-12-09 00:26:06 | ERROR    | ui.lab_selection:refresh_labs:453 | Ошибка при обновлении списка лабораторных работ: 'DatabaseManager' object has no attribute 'get_labs_with_results'
2024-12-09 00:26:22 | ERROR    | ui.lab_selection:refresh_labs:453 | Ошибка при обновлении списка лабораторных работ: 'DatabaseManager' object has no attribute 'get_labs_with_results'
